spring:
  application:
    name: asyncapi-importer-rest

server:
  port: 9004
  tomcat:
    max-threads: 250
    min-spare-threads: 50

logging:
  level:
    root: INFO

cors:
  # Comma-separated list of origins from which this REST service will be called
  allowed-origins: "https://studio.solace.dev,http://localhost:9005,https://feeds.solace.dev"
